/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: The Smithsonian Institution (https://sketchfab.com/Smithsonian)
license: CC0-1.0 (http://creativecommons.org/publicdomain/zero/1.0/)
source: https://sketchfab.com/3d-models/1903-wright-flyer-c91467735c6743af872e65107a79beda
title: 1903 Wright Flyer
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model({ ...props }) {
  const group = useRef();
  const { nodes, materials } = useGLTF("/models/Plane/scene.gltf");

  materials["Default_OBJ"].color = {
    r: 200 / 256,
    g: 35 / 256,
    b: 255 / 256,
  };

  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.06}>
        <mesh
          geometry={nodes.Object_2.geometry}
          material={materials.Default_OBJ}
        />
        <mesh
          geometry={nodes.Object_3.geometry}
          material={materials.Default_OBJ}
        />
        <mesh
          geometry={nodes.Object_4.geometry}
          material={materials.Default_OBJ}
        />
        <mesh
          geometry={nodes.Object_5.geometry}
          material={materials.Default_OBJ}
        />
        <mesh
          geometry={nodes.Object_6.geometry}
          material={materials.Default_OBJ}
        />
        <mesh
          geometry={nodes.Object_7.geometry}
          material={materials["Default_OBJ.001"]}
        />
        <mesh
          geometry={nodes.Object_8.geometry}
          material={materials["Default_OBJ.001"]}
        />
        <mesh
          geometry={nodes.Object_9.geometry}
          material={materials["Default_OBJ.001"]}
        />
        <mesh
          geometry={nodes.Object_10.geometry}
          material={materials["Default_OBJ.001"]}
        />
        <mesh
          geometry={nodes.Object_11.geometry}
          material={materials["Default_OBJ.001"]}
        />
        <mesh
          geometry={nodes.Object_12.geometry}
          material={materials["Default_OBJ.002"]}
        />
        <mesh
          geometry={nodes.Object_13.geometry}
          material={materials["Default_OBJ.002"]}
        />
        <mesh
          geometry={nodes.Object_14.geometry}
          material={materials["Default_OBJ.002"]}
        />
        <mesh
          geometry={nodes.Object_15.geometry}
          material={materials["Default_OBJ.002"]}
        />
        <mesh
          geometry={nodes.Object_16.geometry}
          material={materials["Default_OBJ.002"]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/models/Plane/scene.gltf");
